HARD_EXCLUDED_CATEGORIES = {
    "en:dietary-supplements",
    "en:bodybuilding-supplements",
    "en:medicine",
    "en:household-cleaner",
    "en:home-garden-household-supplies-laundry-supplies",
    "en:personal-care",
    "en:cosmetic-oil",
    "en:beauty",
    "en:open-pet-food-facts",
}

HARD_EXCLUDED_CATEGORIES.update({
    "en:sunscreen",
    "en:multivitamin",
    "en:vitamin-supplement",
    "en:protein-supplement",
    "en:nutritional-supplement",
    "en:baby-wipes",
    "en:laundry-detergent",
    "en:dog-food",
    "en:hair-spray",
    "en:essential-oil",
    "en:body-lotion",
    "en:hand-soap",
    "en:antiperspirant",
    "en:body-oil",
    "en:dishwashing-liquid",
    "en:facial-cleanser",
    "en:nicotine-pouch",
    "en:baby-lotion",
    "en:fabric-softener",
    "en:wet-wipes",
    "en:hair-oil",
    "en:electrolyte-supplement",
    "en:multivitamin-gummies",
    "en:vitamin-gummies",
    "en:herbal-supplement",
    "en:hair-mask",
    "en:hair-conditioner",
    "en:cologne",
    "en:diaper-rash-cream",
    "en:diaper-rash-treatment",
    "en:dog-biscuits",
    "en:cough-drops",
    "en:supplement",
    "en:bath-salts",
    "en:hair-detangler",
    "en:facial-mask",
    "en:baby-powder",
    "en:deodorant",
    "en:vitamin-supplements",
    "en:liquid-soap",
    "en:medical-food",
    "en:lip-balm",
    "en:dog-treats",
    "en:collagen-supplement",
})

FOOD_LIKE_CATEGORIES = {
    "en:protein-bars",
    "en:energy-bars",
    "en:protein-shakes",
}

CATEGORY_RULES = [
    ("Beverages", {
        "en:beverages",
        "en:sodas",
        "en:juices-and-nectars",
        "en:waters",
        "en:teas",
        "en:coffees",
        "en:herbal-teas",
        "en:fruit-drink",
        "en:juice",
        "en:soft-drink",
        "en:drink-mix",
        "en:powdered-drink-mix",
        "en:instant-beverages",
        "en:soft-drinks",
        "en:flavored-and-enhanced-water-drink-mix",
    }),

    ("Snacks", {
        "en:snacks",
        "en:salty-snacks",
        "en:chips-and-fries",
        "en:crisps",
        "en:crackers",
        "en:snack-bar",
        "en:meat-snack",
        "en:meat-snacks",
        "en:trail-mix",
        "en:breakfast-bar",
        "en:puffed-snacks",
        "en:puffed-snack",
        "en:cheese-puffs",
        "en:fruit-crisps",
        "en:chips",
        "en:energy-balls",
        "en:snack-mix",
        "en:cereal-snack",
        "en:corn-snacks",
        "en:corn-snack",
        "en:fruit-chips",
        "en:rice-cakes",
        "en:vegetable-chips",
        "en:fruit-bar",
        "en:chips-and-crisps"
    }),

    ("Dairy", {
        "en:dairies",
        "en:cheeses",
        "en:milks",
        "en:yogurts",
        "en:dairy-substitutes",
        "en:milk-substitutes",
        "en:creamer",
        "en:yogurt-snack",
    }),

    ("Condiments & Sauces", {
        "en:condiments",
        "en:sauces",
        "en:hot-sauces",
        "en:vinegars",
        "en:salsa",
        "en:pickles",
        "en:fruit-spread",
        "en:pickled-jalapeno",
    }),

    ("Baby Food", {
        "en:baby-foods",
        "en:baby-formula",
        "en:baby-food-puree",
        "en:baby-cereal",
        "en:fruit-and-vegetable-puree",
        "en:fruit-pouch",
    }),

    ("Breakfast", {
        "en:breakfasts",
        "en:breakfast-cereals",
    }),

    ("Meat & Seafood", {
        "en:meats-and-their-products",
        "en:meats",
        "en:prepared-meats",
        "en:seafood",
        "en:chicken-and-its-products",
        "en:meat-alternatives",
        "en:meat-analogues",
        "en:chicken-fillets",
        "en:prepared-chicken",
        "en:hot-dogs",
        "en:meatballs",
    }),

    ("Frozen Foods", {
        "en:frozen-foods",
    }),

    ("Desserts & Sweets", {
        "en:desserts",
        "en:frozen-desserts",
        "en:ice-creams-and-sorbets",
        "en:ice-creams",
        "en:chocolate-confection",
        "en:chocolate-confectionery",
        "en:chocolate-cluster",
        "en:pies",
        "en:cookie-dough",
    }),

    ("Bakery", {
        "en:breads",
        "en:biscotti",
        "en:sandwich-rolls",
        "en:tortillas",
        "en:corn-tortillas",
    }),

    ("Prepared Meals", {
        "en:meals",
    }),

    ("Pantry", {
        "en:pastas",
        "en:canned-foods",
        "en:cooking-helpers",
        "en:sweeteners",
        "en:vegetable-oils",
        "en:syrups",
        "en:flours",
        "en:cooking-oil",
        "en:seasoning-mix",
        "en:broths",
        "en:chocolate-chips",
        "en:frosting",
        "en:coffee-pods",
        "en:canned-pasta",
        "en:bone-broth",
        "en:cooking-spray",
        "en:hot-chocolate",
        "en:cocoa-and-its-products",
        "en:cocoa-and-chocolate-powders",
        "en:cocoa-powders",
    }),

    ("Produce", {
        "en:fruits",
        "en:vegetables",
        "en:fruits-based-foods",
        "en:vegetables-based-foods",
        "en:potatoes",
        "en:potatoes-and-their-products",
        "en:salad",
    }),

    ("Nuts, Seeds & Legumes", {
        "en:nuts",
        "en:nuts-and-their-products",
        "en:seeds",
        "en:legumes",
        "en:legumes-and-their-products",
        "en:pulses",
        "en:legume-seeds",
        "en:nuts-and-seeds",
    }),

    ("Spreads", {
        "en:spreads",
        "en:plant-based-spreads",
        "en:nut-butters",
        "en:peanut-butters",
        "en:legume-butters",
        "en:oilseed-purees",
    }),

    ("Dried Foods", {
        "en:dried-products",
        "en:dried-plant-based-foods",
        "en:dried-fruits",
    }),

    ("Sandwiches", {
        "en:sandwiches",
    }),

    ("Eggs", {
        "en:eggs",
    }),

    ("Fruit Snacks", {
        "en:fruit-snack",
        "en:fruit-puree",
    }),

    ("Sports & Protein", {
        "en:protein-bars",
        "en:protein-shakes",
        "en:protein-drink",
        "en:sports-drink",
        "en:electrolyte-drink",
        "en:sports-nutrition",
        "en:electrolyte-drink-mix",
        "en:nutritional-shake",
        "en:meal-replacement-shake",
        "en:whey-protein",
    }),

    ("Candy", {
        "en:gummy-candies",
        "en:gummies",
    })
]