spring.application.name=granker-backend
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/granker}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

app.frontend-url=${FRONTEND_URL:http://localhost:5173}
app.seed.enabled=${SEED_ENABLED:true}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:false}