spring.application.name=granker-backend

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/granker}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

app.frontend-url=${FRONTEND_URL:http://localhost:5173}
app.seed.enabled=${SEED_ENABLED:false}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}

app.admin.create-enabled=${ADMIN_CREATE_ENABLED:false}
app.admin.username=${ADMIN_USERNAME:}
app.admin.email=${ADMIN_EMAIL:}
app.admin.password=${ADMIN_PASSWORD:}

server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never